### PR TITLE
Master

### PR DESCRIPTION
**Pull request by johnastech**

### CODE REVIEW

**Comment by revolter** [comment]
What's with this PR?!

**Comment by nathan-osman** [comment]
Good question. It appears that the request is to merge commits from `master` into the (now-defunct) `ember-update` branch. I should probably delete the branch to avoid confusion.

**Comment by krzysztof-sikorski** [comment]
To me it appears like an excercise in using GitHub...

**Comment by revolter** [comment]
Can't this be deleted?

**Comment by mirkoperillo** [comment]
Maybe yes, it seems to be the unique activity on github of @johnastech.

@johnastech, is it an error ? Can this PR be closed ?

**Comment by revolter** [comment]
@mirkoperillo, I noticed it too. And I think I get notifications for this PR whenever a commit on the master branch is made.

**Comment by revolter** [comment]
And yet again, this showed up in my GitHub notifications with the message `revolter and others added some commits 3 hours ago`. @nathan-osman, please close this PR

**Comment by nathan-osman** [comment]
I've closed this for now. Hopefully the messages stop.

**Comment by revolter** [comment]
Well, they didn't. I'm going to report the user and will write GitHub to completely delete this PR. It got very very annoying.

**Comment by set-killer** [comment]
In the right section there is an ```Unsubscribe``` button ------------------------------->>>--------->>>

**Comment by set-killer** [comment]
In the right section there is an ```Unsubscribe``` button ------------------------------->>>--------->>>

**Comment by revolter** [comment]
I am subscribed to the whole repository. Even if I unsubscribe, this PR still wouldn't make sense. It tries to merge the actual repo's master branch in another repo's branch.

**Comment by set-killer** [comment]
true

**Pull request closed without merging**
